name: "Terraform Windows Check"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Plan on Windows"
    runs-on: windows-latest  # Windows環境を指定

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
              # -input=false を追加して、入力を待たずに強制実行させる
              # さらに、詳細なデバッグログ（TF_LOG）を出す設定を一時的に追加
              run: terraform plan -input=false
              env:
                TF_LOG: INFO